### ISSUE TITLE
Bayer filter example

### ISSUE THREAD

**Issue by f4bsch** [codeplaysoftware/visioncpp#18]
https://github.com/codeplaysoftware/visioncpp/blob/master/examples/bayer_filter.cpp#L162

should be 
```
uchar B3 = bayer.at(bayer.I_c, bayer.I_r + 2)[0];
```
(Its currently the same as line 160, top neighbor blue pixel)

**Comment by lukeiwanski** [comment]
@marcelsheeny  could you have a look at this?

**Comment by marcelsheeny** [comment]
I just fixed it! Thanks @f4bsch !
