### ISSUE TITLE
Greyscale Sample-Not getting correct output

### ISSUE THREAD

**Issue by Chithra-Intel** [codeplaysoftware/visioncpp#28]
While running greyscale sample available in the visioncpp github repo, I am getting a noise image as output.
PFA the attached input and output image.

OS: Ubuntu 18.04.3 
computcpp -1.2.0
opencv- 4.1.1
![flower_input](https://user-images.githubusercontent.com/58719918/71884266-fcba2a80-315d-11ea-9a68-4d075fe6e1cd.png)
![flower_output1](https://user-images.githubusercontent.com/58719918/71884288-05aafc00-315e-11ea-8336-14d5e8aad757.png)

**Comment by rodburns** [comment]
Can I suggest you try ComputeCpp v1.0.2? That was the last version I tested this with. Then in the meantime we are looking at how to update this for the latest ComputeCpp version.

**Comment by rodburns** [comment]
We've been able to test this now and it is working fine using the webcam on a machine using Ubuntu with the latest ComputeCpp. I assume you needed to make code modifications to get it to output a single frame, I'd suggest you look at that code to narrow down where things are going wrong. I'd check the input data you are providing to the VisionCpp method call is correct to start with.

**Comment by Chithra-Intel** [comment]
Thanks for your reply. It's working fine for me with the latest ComputeCpp version.It was a small mistake from my side.
